In [6]:
import numpy as np

# Given data
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

print("Task 1")
print("───────")

# Print shape of the array
print("Shape of data:", data.shape)

# Mean temperature per station (mean along axis=1 → per row)
mean_per_station = data.mean(axis=1)
print("\nMean temperature per station:")
for i, mean_temp in enumerate(mean_per_station, 1):
    print(f"Station {i}: {mean_temp:.2f} °C")

print("\nTask 2")
print("───────")

# Boolean mask: temperatures > 28.0
mask = data > 28.0

# Extract matching values and flatten to 1D
high_temps = data[mask]
print("Temperatures above 28.0°C (as 1D array):")
print(high_temps)

print("\nTask 3")
print("───────")

# Normalize to [0, 1]
data_min = data.min()
data_max = data.max()
normalized = (data - data_min) / (data_max - data_min)

# Round to 2 decimal places and print
print("Normalized data (rounded to 2 decimal places):")
print(np.round(normalized, 2))

Task 1
───────
Shape of data: (4, 5)

Mean temperature per station:
Station 1: 25.30 °C
Station 2: 23.78 °C
Station 3: 26.58 °C
Station 4: 25.26 °C

Task 2
───────
Temperatures above 28.0°C (as 1D array):
[31.2 28.7 30.5 33.1 29.6 31.9 28.1]

Task 3
───────
Normalized data (rounded to 2 decimal places):
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
